### ISSUE TITLE
Add indicator of maintainence mode

### ISSUE THREAD

**Issue by bwinterton** [byuoitav/smee#8]
There should be an easily identifiable marker to show which alerts are in maintenance mode when the filter is disabled.

**Comment by bwinterton** [comment]
@thailandmatt Do you have a preference on how this should look?

**Comment by thailandmatt** [comment]
kind of like labels in github - just a little bubble was what I was envisioning.

**Comment by bwinterton** [comment]
For visual's sake, this is what Matt is talking about: 
![image](https://user-images.githubusercontent.com/5790659/123162939-6b607600-d42e-11eb-8264-888fb365553d.png)
